### ISSUE TITLE
Custom buttons for triggering events on a specific participant's browser are hidden by zoom UI

### ISSUE THREAD

**Issue by maddalihanumateja** [maddalihanumateja/ParticipateInRemoteDesign#1]
I generate a couple of buttons, projector_button and printer_button, in index.js after the researcher has started a meeting. The zmmtg-root div seems to hide them behind it. These buttons need to appear on the zoom UI (maybe as additional buttons on the wc-left-footer div). Maybe I also need to change their class so the browser automatically shows them above the Zoom UI. Alternatively, I can restrict the zoom UI to an iframe and place my own custom buttons around this iframe.

**Comment by ameliashort331** [comment]
This issue is solved with the latest [pull request](https://github.com/maddalihanumateja/ParticipateInRemoteDesign/pull/48) to add custom buttons dynamically for the researcher's UI.
